### ISSUE TITLE
Disable stats for https://musicpua.firebaseapp.com/

### ISSUE THREAD

**Issue by ngokevin** [FlexingDream/aframe_demo#1]
This is amazing! I want to share it, can you disable the stats?

Just remove stats from `<a-scene stats>`

**Comment by ngokevin** [comment]
Nevermind, I found http://flexingdream.github.io/aframe_demo/

**Comment by ngokevin** [comment]
Nevermind, that's different :)

**Comment by ngokevin** [comment]
@mattpua Would love to feature this on our release blog post if we could remove those stats :)

**Comment by gching** [comment]
@ngokevin It should have the stats removed now :). Sorry for the delay and thank you for featuring! Let us know if you need anything else!

**Comment by ngokevin** [comment]
Thanks!
